### ISSUE TITLE
Build warning in file main.c

### ISSUE THREAD

**Issue by panosmaurikos** [unikraft/app-elfloader#12]
@razvand @StefanJum 
In file included from /home/fstain/Desktop/unicraft/hackathon/unikraft/lib/vfscore/main.c:55:
/home/fstain/Desktop/unicraft/hackathon/unikraft/lib/vfscore/main.c:2422:96: warning: argument 3 of type ‘const struct timespec *’ declared as a pointer [-Warray-parameter=]
 2422 | UK_SYSCALL_R_DEFINE(int, utimensat, int, dirfd, const char*, pathname, const struct timespec*, times, int, flags)
      |                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/fstain/Desktop/unicraft/hackathon/unikraft/lib/syscall_shim/include/uk/syscall.h:190:41: note: in definition of macro ‘UK_S_ARG_ACTUAL’
  190 | #define UK_S_ARG_ACTUAL(type, arg) type arg
      |                                         ^~~
/home/fstain/Desktop/unicraft/hackathon/unikraft/lib/syscall_shim/include/uk/syscall.h:171:55: note: in expansion of macro ‘UK_ARG_MAP4’
  171 | #define  UK_ARG_MAP6(m, type, arg, ...) m(type, arg), UK_ARG_MAP4(m, __VA_ARGS__)
      |                                                       ^~~~~~~~~~~
/home/fstain/Desktop/unicraft/hackathon/unikraft/lib/syscall_shim/include/uk/syscall.h:172:55: note: in expansion of macro ‘UK_ARG_MAP6’
  172 | #define  UK_ARG_MAP8(m, type, arg, ...) m(type, arg), UK_ARG_MAP6(m, __VA_ARGS__)
      |                                                       ^~~~~~~~~~~
/home/fstain/Desktop/unicraft/hackathon/unikraft/include/uk/essentials.h:171:29: note: in expansion of macro ‘UK_ARG_MAP8’
  171 | #define __UK_CONCAT_X(a, b) a##b
      |                             ^
/home/fstain/Desktop/unicraft/hackathon/unikraft/lib/syscall_shim/include/uk/syscall.h:363:20: note: in expansion of macro ‘UK_ARG_MAPx’
  363 |         rtype name(UK_ARG_MAPx(x, UK_S_ARG_ACTUAL, __VA_ARGS__))        \
      |                    ^~~~~~~~~~~
/home/fstain/Desktop/unicraft/hackathon/unikraft/lib/syscall_shim/include/uk/syscall.h:374:35: note: in expansion of macro ‘__UK_SYSCALL_R_DEFINE’
  374 | #define _UK_SYSCALL_R_DEFINE(...) __UK_SYSCALL_R_DEFINE(__VA_ARGS__)
      |                                   ^~~~~~~~~~~~~~~~~~~~~
/home/fstain/Desktop/unicraft/hackathon/unikraft/lib/syscall_shim/include/uk/syscall.h:376:9: note: in expansion of macro ‘_UK_SYSCALL_R_DEFINE’
  376 |         _UK_SYSCALL_R_DEFINE(UK_NARGS(__VA_ARGS__),                     \
      |         ^~~~~~~~~~~~~~~~~~~~
/home/fstain/Desktop/unicraft/hackathon/unikraft/lib/vfscore/main.c:2422:1: note: in expansion of macro ‘UK_SYSCALL_R_DEFINE’
 2422 | UK_SYSCALL_R_DEFINE(int, utimensat, int, dirfd, const char*, pathname, const struct timespec*, times, int, flags)
      | ^~~~~~~~~~~~~~~~~~~
In file included from /home/fstain/Desktop/unicraft/hackathon/unikraft/lib/vfscore/main.c:36:
/home/fstain/Desktop/unicraft/hackathon/unikraft/lib/nolibc/include/sys/stat.h:120:34: note: previously declared as an array ‘const struct timespec[2]’
  120 | int utimensat(int, const char *, const struct timespec [2], int);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/fstain/Desktop/unicraft/hackathon/unikraft/lib/vfscore/main.c:2444:45: warning: argument 2 of type ‘const struct timespec *’ declared as a pointer [-Warray-parameter=]
 2444 | int futimens(int fd, const struct timespec *times)
      |                      ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/fstain/Desktop/unicraft/hackathon/unikraft/lib/nolibc/include/sys/stat.h:119:19: note: previously declared as an array ‘const struct timespec[2]’
  119 | int futimens(int, const struct timespec [2]);

**Comment by razvand** [comment]
**Hackathon points**: 5

**Comment by razvand** [comment]
This was solved by #17
