### ISSUE TITLE
brk syscall returns wrong values 

### ISSUE THREAD

**Issue by marcrittinghaus** [unikraft/app-elfloader#14]
### Problem

The `brk` syscall returns `ERR2PTR(-ENOMEM)` on error. However, according to the man-page [1] the syscall shall return the current program break on failure and the new program break on success.

Accordingly, the libc wrapper needs to be adapted to reflect this behavior.

[1] https://man7.org/linux/man-pages/man2/brk.2.html

**Comment by razvand** [comment]
@andraprs, has this been fixed by #15 ?

**Comment by andraprs** [comment]
> @andraprs, has this been fixed by #15 ?

Yes, this should have been fixed by the updates from the mentioned PR.

If there is any remaining case that is not covered, please reopen this GitHub issue or create one. Thank you.
