### ISSUE TITLE
Stack is not aligned to a 16-byte boundary before executing the ELF binary

### ISSUE THREAD

**Issue by csvancea** [unikraft/app-elfloader#8]
### Problem

Current builds of glibc use SSE instructions to read/write data from/to stack, especially when dealing with variadic arguments (eg, `printf`).

According to the x86_64 ABI, the stack must be aligned to a 16-byte boundary when a function is entered and gcc generates code that (rightly) assumes so.

### Repro

Compile the following program as a dynamically-linked ELF and run it with a different number of arguments:

```c
// gcc -o helloworld helloworld.c

#include <stdio.h>

int main(int argc, char **argv)
{
    for (int i = 0; i < argc; ++i)
    {
        printf("[%d] %s\n", i, argv[i]);
    }
    return 0;
}
```

- Example of 'good' invokation:
`qemu-guest -k app-elfloader_kvm-x86_64 -i rootfs/ld-linux-x86-64.so.2 -e rootfs -a "/ld-linux-x86-64.so.2 --library-path / /helloworld dummy1"`

- Example of 'bad invokation' (odd number of arguments pushed to the stack --> crash):
`qemu-guest -k app-elfloader_kvm-x86_64 -i rootfs/ld-linux-x86-64.so.2 -e rootfs -a "/ld-linux-x86-64.so.2 --library-path / /helloworld dummy1 dummy2"`

I have also attached a zip archive with the exact [binaries](https://github.com/unikraft/app-elfloader/files/11009004/rootfs.zip) I am using.

### Environment

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
ld.so (Ubuntu GLIBC 2.35-0ubuntu3.1) stable release version 2.35

**Comment by skuenzer** [comment]
Good point. I am linking to PR #9 to solve this issue. The PR is currently under review.

**Comment by andraprs** [comment]
PR https://github.com/unikraft/app-elfloader/pull/9 has been merged.
